# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'run.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(640, 330)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setMaximumSize(QtCore.QSize(640, 330))
        self.m_chooseFile = QtWidgets.QPushButton(Dialog)
        self.m_chooseFile.setGeometry(QtCore.QRect(10, 10, 620, 25))
        self.m_chooseFile.setObjectName("m_chooseFile")
        self.m_sourceBox = QtWidgets.QGroupBox(Dialog)
        self.m_sourceBox.setGeometry(QtCore.QRect(10, 40, 620, 80))
        self.m_sourceBox.setObjectName("m_sourceBox")
        self.m_sourceSlider = QtWidgets.QSlider(self.m_sourceBox)
        self.m_sourceSlider.setGeometry(QtCore.QRect(10, 30, 600, 16))
        self.m_sourceSlider.setOrientation(QtCore.Qt.Horizontal)
        self.m_sourceSlider.setObjectName("m_sourceSlider")
        self.widget = QtWidgets.QWidget(self.m_sourceBox)
        self.widget.setGeometry(QtCore.QRect(190, 50, 254, 28))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.m_playSource = QtWidgets.QPushButton(self.widget)
        self.m_playSource.setObjectName("m_playSource")
        self.horizontalLayout.addWidget(self.m_playSource)
        self.m_pauseSource = QtWidgets.QPushButton(self.widget)
        self.m_pauseSource.setObjectName("m_pauseSource")
        self.horizontalLayout.addWidget(self.m_pauseSource)
        self.m_stopSource = QtWidgets.QPushButton(self.widget)
        self.m_stopSource.setObjectName("m_stopSource")
        self.horizontalLayout.addWidget(self.m_stopSource)
        self.m_startSeparation = QtWidgets.QPushButton(Dialog)
        self.m_startSeparation.setGeometry(QtCore.QRect(10, 120, 620, 25))
        self.m_startSeparation.setObjectName("m_startSeparation")
        self.m_voiceBox = QtWidgets.QGroupBox(Dialog)
        self.m_voiceBox.setGeometry(QtCore.QRect(10, 150, 620, 80))
        self.m_voiceBox.setObjectName("m_voiceBox")
        self.m_voiceSlider = QtWidgets.QSlider(self.m_voiceBox)
        self.m_voiceSlider.setGeometry(QtCore.QRect(10, 30, 600, 16))
        self.m_voiceSlider.setOrientation(QtCore.Qt.Horizontal)
        self.m_voiceSlider.setObjectName("m_voiceSlider")
        self.layoutWidget_2 = QtWidgets.QWidget(self.m_voiceBox)
        self.layoutWidget_2.setGeometry(QtCore.QRect(190, 50, 254, 28))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.m_playVoice = QtWidgets.QPushButton(self.layoutWidget_2)
        self.m_playVoice.setObjectName("m_playVoice")
        self.horizontalLayout_3.addWidget(self.m_playVoice)
        self.m_pauseVoice = QtWidgets.QPushButton(self.layoutWidget_2)
        self.m_pauseVoice.setObjectName("m_pauseVoice")
        self.horizontalLayout_3.addWidget(self.m_pauseVoice)
        self.m_stopVoice = QtWidgets.QPushButton(self.layoutWidget_2)
        self.m_stopVoice.setObjectName("m_stopVoice")
        self.horizontalLayout_3.addWidget(self.m_stopVoice)
        self.m_musicBox = QtWidgets.QGroupBox(Dialog)
        self.m_musicBox.setGeometry(QtCore.QRect(10, 240, 620, 80))
        self.m_musicBox.setObjectName("m_musicBox")
        self.m_musicSlider = QtWidgets.QSlider(self.m_musicBox)
        self.m_musicSlider.setGeometry(QtCore.QRect(10, 30, 600, 16))
        self.m_musicSlider.setOrientation(QtCore.Qt.Horizontal)
        self.m_musicSlider.setObjectName("m_musicSlider")
        self.layoutWidget_3 = QtWidgets.QWidget(self.m_musicBox)
        self.layoutWidget_3.setGeometry(QtCore.QRect(190, 50, 254, 28))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.layoutWidget_3)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.m_playMusic = QtWidgets.QPushButton(self.layoutWidget_3)
        self.m_playMusic.setObjectName("m_playMusic")
        self.horizontalLayout_4.addWidget(self.m_playMusic)
        self.m_pauseMusic = QtWidgets.QPushButton(self.layoutWidget_3)
        self.m_pauseMusic.setObjectName("m_pauseMusic")
        self.horizontalLayout_4.addWidget(self.m_pauseMusic)
        self.m_stopMusic = QtWidgets.QPushButton(self.layoutWidget_3)
        self.m_stopMusic.setObjectName("m_stopMusic")
        self.horizontalLayout_4.addWidget(self.m_stopMusic)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Выделение источников"))
        self.m_chooseFile.setText(_translate("Dialog", "Выбрать файл"))
        self.m_sourceBox.setTitle(_translate("Dialog", "Исходный файл"))
        self.m_playSource.setText(_translate("Dialog", "▶️"))
        self.m_pauseSource.setText(_translate("Dialog", "||"))
        self.m_stopSource.setText(_translate("Dialog", "■"))
        self.m_startSeparation.setText(_translate("Dialog", "Разделить"))
        self.m_voiceBox.setTitle(_translate("Dialog", "Вокал"))
        self.m_playVoice.setText(_translate("Dialog", "▶️"))
        self.m_pauseVoice.setText(_translate("Dialog", "||"))
        self.m_stopVoice.setText(_translate("Dialog", "■"))
        self.m_musicBox.setTitle(_translate("Dialog", "Аккомпанемент"))
        self.m_playMusic.setText(_translate("Dialog", "▶️"))
        self.m_pauseMusic.setText(_translate("Dialog", "||"))
        self.m_stopMusic.setText(_translate("Dialog", "■"))

